# 服务端口，名
server:
  port: 9903
spring:
  application:
    name: aliyun-message


aliyun.accessKeyId: "阿里云里找"
aliyun.accessSecret: "阿里云里找"

#aliyun短信服务
aliyun.SignName: "Shenzc商城"
aliyun.TemplateCode: "SMS_173476912"
aliyun.RegionId: "cn-hangzhou"
aliyun.sysDomain: "dysmsapi.aliyuncs.com"
aliyun.sysVersion: "2017-05-25"
aliyun.sysAction: "SendSms"

#aliyun oss上传服务
aliyun.endpoint: "https://oss-cn-beijing.aliyuncs.com"
aliyun.bucketName: "edu-shenzc"
aliyun.fileHost: "blog"