spring:
  application:
    name: article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://114.55.146.217:3306/blog?useUnicode=true&characterEncoding=UTF-8
    #可以配置也可以不配置，会根据url自动识别
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      #全局逻辑删除，只要实体类中字段又isDelete，将做逻辑删除（或者不配置，在实体类中字段上加上@TableLogic注解）
      logic-delete-field: isDelete
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
server:
  port: 9902
